trigger: none


schedules:
- cron: "0 16 * * *"
  displayName: Daily AI Test Generator (6 PM Egypt)
  always: true


pool:
  vmImage: ubuntu-latest

variables:
- group: AI-Test-Generator-Vars

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: pip install -r requirements.txt
  displayName: Install Dependencies

- script: python scripts/main.py
  displayName: Run Hierarchical AI Test Generator
  env:
    AZURE_PAT: $(AZURE_PAT)
    GEMINI_API_KEY: $(GEMINI_API_KEY)
    AZURE_ORG: $(AZURE_ORG)
    AZURE_PROJECT: $(AZURE_PROJECT)
    ASSIGNED_TO_EMAIL: $(AZURE_EMAIL)