trigger: none

schedules:
- cron: "0 * * * *"
  displayName: Hourly AI Traceable Test Generator
  always: true

pool:
  vmImage: ubuntu-latest

variables:
  AZURE_ORG: "your-org"
  AZURE_PROJECT: "your-project"

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: pip install -r requirements.txt
  displayName: Install Dependencies

- script: python scripts/main.py
  displayName: Run Hierarchical AI Test Generator
  env:
    AZURE_PAT: $(AZURE_PAT)
    GEMINI_API_KEY: $(GEMINI_API_KEY)
