trigger: none

schedules:
- cron: "0 16 * * *"              # Runs at 16:00 UTC = 18:00 Egypt time
  displayName: Daily AI Test Generator (6 PM Egypt)
  branches:
    include:
      - main                      # main branch runner
  always: true                    # Run even if there are no recent changes

pool:
  name: 'Validation Agent'

variables:
- group: AI-Test-Generator-Vars

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: pip install -r requirements.txt
  displayName: Install Dependencies

- script: python scripts/main.py
  displayName: Run Hierarchical AI Test Generator
  env:
    AZURE_PAT: $(AZURE_PAT)
    GEMINI_API_KEY: $(GEMINI_API_KEY)
    AZURE_ORG: $(AZURE_ORG)
    AZURE_PROJECT: $(AZURE_PROJECT)
    ASSIGNED_TO_EMAIL: $(AZURE_EMAIL)